name: Size Limit

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    name: Size Limit Check
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Dependencies
        id: deps
        uses: actions/cache@v2
        with:
          path: './node_modules'
          key: deps-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Size Limit
        uses: andresz1/size-limit-action@v1
        with:
          build_script: build:release
          skip_step: install
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clean_script: clean
